config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :connections
      
    end
  end  
      # Defines the root path route ("/")
      # root "articles#index"
  
  root 'portal#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/connection.rb
class Connection < ApplicationRecord
end

app/models/portal.rb
class Portal < ApplicationRecord
end

app/controllers/api/v1/connections_controller.rb
class Api::V1::ConnectionsController < ApplicationController
  before_action :set_connections, only: %i[ show edit update destroy ]

  # GET /connections or /connections.json
  def index
    @connections = Connection.all
    render json: @connections
  end

  # GET /connections/1 or /connections/1.json
  def show
    @connections = User.find(params[:id])
    render json: @connections
  end

  # GET /connections/new
  def new
    @connections = Connections.new
  end

  # GET /connections/1/edit
  def edit
  end

  # POST /connections or /connections.json
  def create
    @connections = Connections.new(connection_params)

    respond_to do |format|
      if @connections.save
        format.html { redirect_to connections_url(@connection), notice: "Connection was successfully created." }
        format.json { render :show, status: :created, location: @connections }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @connections.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /connections/1 or /connections/1.json
  def update
    respond_to do |format|
      if @connections.update(connections_params)
        format.html { redirect_to connections_url(@connections), notice: "Connection was successfully updated." }
        format.json { render :show, status: :ok, location: @connections }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @connections.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /connections/1 or /connections/1.json
  def destroy
    @connections.destroy

    respond_to do |format|
      format.html { redirect_to connections_url, notice: "Connection was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_connections
      @connections = Connections.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def connections_params
      params.require(:connections).permit(:type, :tag, :description, :origin)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/portal_controller.rb
class PortalController < ApplicationController
  def index
    @portal = Portal.all
  end
 
  def show
      @portal = Portal.find(params[:id])
  end
   
  def new
      @portal = Portal.new
  end

  def create
      @portal = Portal.new(portal_params)
      if @portal.save
          redirect_to @portal
      else
          render 'new'
      end
  end
 
  def edit
      @portal = Portal.find(params[:id])
  end

  def update
      @portal = Portal.find(params[:id])
      if @portal.update(portal_params)
          redirect_to @portal
      else
          render 'edit'
      end
  end



  def destroy
      @portal = Portal.find(params[:id])
      @portal.destroy

      redirect_to portals_path
  end    
 
  private
      def portal_params
          params.require(:portal).permit(:name)
      end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/helpers/portal_helper.rb
module PortalHelper
end

app/views/connections/_connection.html.erb
<div id="<%= dom_id connection %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Type:</strong>
    <%= connection.type %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Tag:</strong>
    <%= connection.tag %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= connection.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Origin:</strong>
    <%= connection.origin %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this connection", connection, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this connection', edit_connection_path(connection), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/connections/_form.html.erb
<%= form_with(model: connection, class: "contents") do |form| %>
  <% if connection.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(connection.errors.count, "error") %> prohibited this connection from being saved:</h2>

      <ul>
        <% connection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :type %>
    <%= form.text_field :type, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :tag %>
    <%= form.text_area :tag, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :origin %>
    <%= form.text_field :origin, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/connections/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing connection</h1>

  <%= render "form", connection: @connection %>

  <%= link_to "Show this connection", @connection, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to connections", connections_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/connections/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Connections</h1>
    <%= link_to 'New connection', new_connection_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="connections" class="min-w-full">
    <%= render @connections %>
  </div>
</div>

app/views/connections/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New connection</h1>

  <%= render "form", connection: @connection %>

  <%= link_to 'Back to connections', connections_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/connections/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @connection %>

    <%= link_to 'Edit this connection', edit_connection_path(@connection), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this connection', connection_path(@connection), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to connections', connections_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Takehome</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body>



    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/portal/index.html.erb
<h1 class="mb-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Welcome to Portal Viewer</h1>



<div class="grid grid-cols-3 gap-4 ...">
 
 
  <p class="mb-6 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48 dark:text-gray-400">Planear ... mostrar alerta de conexion - </p></div>
  <p class="mb-6 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48 dark:text-gray-400"> - registrar commits en git - </p></div> 
  <p class="mb-6 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48 dark:text-gray-400"> - mostrar conexiones de apis - </p> </p></div>
  <p class="mb-6 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48 dark:text-gray-400"> - mostrar cierres de apis - </p> </p></div>
  <p class="mb-6 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48 dark:text-gray-400"> - registrar logeos de usuarios - </p></div>
    
</div>